### ISSUE TITLE
Cannot build due to AttributeError: module 'chainer.functions' has no attribute 'roi_max_pooling_2d'

### ISSUE THREAD

**Issue by kumasento** [pfnet-research/chainer-compiler#152]
Hello, I was trying to build `chainer-compiler` but met this issue:

```log
[  0%] Generating stamp_out/ch2o_node_SoftmaxClossEntropy
Traceback (most recent call last):
  File "/home/ruizhe/projects/chainer-compiler/ch2o/tests/node/SoftmaxClossEntropy.py", line 18, in <module>
    import ch2o
  File "/home/ruizhe/projects/chainer-compiler/ch2o/ch2o/__init__.py", line 1, in <module>
    from ch2o.chainer2onnx import compile_model
  File "/home/ruizhe/projects/chainer-compiler/ch2o/ch2o/chainer2onnx.py", line 25, in <module>
    from ch2o.funcs import Func, Func2NodeClass, Function_Concat, Function_Dummy, castto
  File "/home/ruizhe/projects/chainer-compiler/ch2o/ch2o/funcs.py", line 585, in <module>
    (F.roi_max_pooling_2d, Function_ROIMaxPool2d),
AttributeError: module 'chainer.functions' has no attribute 'roi_max_pooling_2d'
CMakeFiles/node_SoftmaxClossEntropy.dir/build.make:71: recipe for target 'stamp_out/ch2o_node_SoftmaxClossEntropy' failed
make[2]: *** [stamp_out/ch2o_node_SoftmaxClossEntropy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/node_SoftmaxClossEntropy.dir/all' failed
make[1]: *** [CMakeFiles/node_SoftmaxClossEntropy.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I am not sure why this happens and I will investigate later on. 

Other info:

- commit id: `3a95f55259d1e1ad96fb12974e47714e08ed9a41`
- Not using CUDA

**Comment by shinh** [comment]
You need to install recent chainer. If you are planning to try using the Python interface, you need to install third_party/chainer for binary compatibility, e.g.,
```
$ CHAINER_BUILD_CHAINERX=1 pip3 install third_party/chainer
```
To build and run C++ programs, installing Chainer 6 should be enough:
```
$ pip3 install --pre chainer
```

**Comment by kumasento** [comment]
Many thanks! I’ve missed that CHAINER_BUILD_CHAINERX=1 prefix while installing chainer. I will check and get back to you soon.

**Comment by shinh** [comment]
Hmm the failure is not related to the existence of ChainerX. The failed build command is generating a test case using Chainer and `roi_max_pooling_2d` was not in Chainer 5 (https://github.com/chainer/chainer/pull/5285). Anyway, installing third_party/chainer with CHAINER_BUILD_CHAINERX=1 should work. I hope it fix the issue.

**Comment by kumasento** [comment]
Yes, you're right, the problem is that I haven't correctly override the installed chainer with the one under `third_party/chainer`. This issue can be closed :)

Thank you for all the help!

**Comment by kumasento** [comment]
BTW `CHAINER_BUILD_CHAINERX=1` is necessary if I intend to use CUDA, or there will be an error like this:

```
/chainer-compiler/runtime/ops/nvrtc.cc:94: undefined reference to `typeinfo for chainerx::cuda::CudaDevice'
```
