### ISSUE TITLE
Support functions and links

### ISSUE THREAD

**Issue by durswd** [pfnet-research/chainer-compiler#160]
Functions and layers should be supported as CH2O

## CH2O Testcase

https://github.com/pfnet-research/chainer-compiler/tree/master/ch2o/tests/node

## elichia functions

https://github.com/pfnet-research/chainer-compiler/blob/master/elichika/elichika/parser/functions_builtin.py

https://github.com/pfnet-research/chainer-compiler/blob/master/elichika/elichika/functions_buildin.py

### How to add a function

it is an example.

https://github.com/pfnet-research/chainer-compiler/pull/166

## elichika links

https://github.com/pfnet-research/chainer-compiler/blob/master/elichika/elichika/parser/links_builtin.py

https://github.com/pfnet-research/chainer-compiler/blob/master/elichika/elichika/links_builtin.py

## Rest tests
| Name | Type | Status | CH2O |
|:-----------|------------:|:------------:|:------------:|
| EmbedID.py | Links | | https://github.com/pfnet-research/chainer-compiler/blob/master/ch2o/ch2o/links.py#L455 |
| NStepBiLSTM.py | Links | | https://github.com/pfnet-research/chainer-compiler/blob/master/ch2o/ch2o/links.py#L312 |
| NStepLSTM.py | Links | | https://github.com/pfnet-research/chainer-compiler/blob/master/ch2o/ch2o/links.py#L177 |
| Roi.py | |  not pass | |
| Sum.py | Functions | | https://github.com/pfnet-research/chainer-compiler/blob/master/ch2o/ch2o/funcs.py#L483 |

**Comment by Rishav1** [comment]
#205 Implemented LRN.py. Might as well add that.

**Comment by durswd** [comment]
https://github.com/pfnet-research/chainer-compiler/pull/274
