### ISSUE TITLE
Add custom ONNX domain for chainer

### ISSUE THREAD

**Issue by take-cheeze** [pfnet-research/chainer-compiler#298]
https://github.com/onnx/onnx/blob/5972eed96752551a0ea8b932904fedd568c48d3b/docs/IR.md#models
> Models MUST specify a domain and use reverse domain names based on the responsible organization's identity, the same convention that is traditionally used for naming Java packages.

Define somewhere and replace the domain in:
https://github.com/pfnet-research/chainer-compiler/blob/4ea71725dc37f362d0368af5fcad40b5346a2132/compiler/custom_onnx_ops.cc#L3

**Comment by shinh** [comment]
I agree. I think elichika should set the domain properly first. In addition to ONNX domain, we need to take care of ONNX opset version as well. These info is completely ignored now. Though I'm not sure the priority of this, but we need to handle them eventually.
