### ISSUE TITLE
Add continue/break/return to elichika

### ISSUE THREAD

**Issue by shinh** [pfnet-research/chainer-compiler#327]
A GSoC student is working for it.

**Comment by shinh** [comment]
The first commit: The first commit: https://github.com/pfnet-research/chainer-compiler/pull/311

**Comment by shinh** [comment]
https://github.com/pfnet-research/chainer-compiler/pull/352

https://github.com/pfnet-research/chainer-compiler/pull/370

**Comment by Rishav1** [comment]
#389

**Comment by Rishav1** [comment]
Should we close this issue?

**Comment by shinh** [comment]
Yes. Thanks!
