### ISSUE TITLE
Honor opset_import in ModelProto

### ISSUE THREAD

**Issue by shinh** [pfnet-research/chainer-compiler#747]
Currently, we are ignoring `opset_import` when we run shape inference. Currently, `Graph` and `Node` do not have an access to `Model` nor opset_import, so we need to either

1. add `Graph::model_` and `Node::model_` (or `Node::graph_`)
2. introduce `ModelScope` or something which sets `Model::current_model()` and use it in passes.cc

I'd prefer the latter approach.

Anyway, chainer_compiler_core.cc should be also updated so deprecate `LoadGraph` and introduce `LoadModel` instead.

**Comment by shinh** [comment]
https://github.com/pfnet-research/chainer-compiler/pull/748/commits/b5574aea26b7ec7b5798e26f005d813f258bf69f could be reconsidered after fixing this issue.

**Comment by take-cheeze** [comment]
Merged https://github.com/pfnet-research/chainer-compiler/pull/770 so closing
